# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish Docker images

on:
  push:
    branches: ['main']

jobs:
  push_to_registry:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    env:
      MSSQL1_PASSWORD: ${{ secrets.MSSQL1_PASSWORD }}
      MSSQL2_PASSWORD: ${{ secrets.MSSQL2_PASSWORD }}
      FE_URL: ${{ secrets.FE_URL }}
      FE_PORT: ${{ secrets.FE_PORT }}
      BE_URL: ${{ secrets.BE_URL }}
      BE_PORT: ${{ secrets.BE_PORT }}
      UName: ${{ secrets.UName }}
      Kestrel_Certificates_Default_Password: ${{ secrets.Kestrel_Certificates_Default_Password }}
      IssueSign: ${{ secrets.IssueSign }}
      IssueAudience: ${{ secrets.IssueAudience }}
      InitDb: ${{ secrets.InitDb }}
      GoogleClientSecret: ${{ secrets.GoogleClientSecret }}
      GoogleClientId: ${{ secrets.GoogleClientId }}
      GitHubClientSecret: ${{ secrets.GitHubClientSecret }}
      GitHubClientId: ${{ secrets.GitHubClientId }}
      FacebookClientSecret: ${{ secrets.FacebookClientSecret }}
      FacebookClientId: ${{ secrets.FacebookClientId }}
      ConnectionString: ${{ secrets.ConnectionString }}
      APass: ${{ secrets.APass }}
      AName: ${{ secrets.AName }}
      AEmail: ${{ secrets.AEmail }}
      ACall: ${{ secrets.ACall }}
      VITE_FRONTEND_URL: ${{ secrets.FE_URL }}
      VITE_FRONTEND_PORT: ${{ secrets.FE_PORT }}
      VITE_BACKEND_URL: ${{ secrets.BE_URL }}
      VITE_BACKEND_PORT: ${{ secrets.BE_PORT }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build and push Server Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: "MyCode Backend Server"
          file: "MyCode Backend Server/MyCode Backend Server/Dockerfile"
          push: true
          tags: k1llerrat87/mycode:backend

      - name: Build and push Client Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: "mycodereactserver"
          dockerfile: "mycodereactserver/Dockerfile"
          push: true
          tags: k1llerrat87/mycode:frontend
